#
# Configuration(s) for auto-update.rb
#

admin:
  from: foo@example.com
  to: bar@example.com
  subject: Check results of auto-update.rb %Y-%m-%d %H:%M

users:
 - name: site name (as you want)
   url: http://example.com
   host: foo.example.com
   user: username
   pass: password
   port: 22
   key:
   phrase:
   dir: /path/to/wordpress

 - name: site name (as you want)
   url: http://example.org
   host: bar.example.org
   user: username
   pass:
   port: 22
   key: /path/to/private_key
   phrase: passphrase
   dir: /path/to/wordpress
